appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
driverName = postgres
dataSourceName = user=postgres password=r1k2-throwaway host=r1-k2-pg port=5432 sslmode=disable dbname=casdoor
dbName =
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = ""
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
origin = "http://localhost:38000"
staticBaseUrl = "https://cdn.casbin.org"
